### ISSUE TITLE
[Task] size operator

### ISSUE THREAD

**Issue by pichoemr** [lenra-io/query-parser#29]
## What should be done 
$size is a value operator so we need:

### Grammar
- uncomment $size in value operator

### Exec
- add "$size" case in value-operator exec?
  - checks if the element is an array and if the array size has the specified size

**Comment by shiipou** [comment]
@pichoemr See size operator test problem

**Comment by pichoemr** [comment]
The problem comes from our management of the elements of the list, before executing the size operator we manage the list and call the exec on all the elements of the list we had to add an if to execute on all the list if the operator is `$size`.
